name: HW action

on:
  workflow_dispatch:
  push:
    paths:
      - 'hw/**'
      - '.github/**'

jobs:
  kibot:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Kibot
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: ./hw/.kibot.yaml
          dir: ./hw
          board: ./hw/EM-Template.kicad_pcb
          schema: ./hw/EM-Template.kicad_sch

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HW-kibot
          path: |
            hw/doc
            hw/bom
            hw/fab

  mems:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup KiCAD
        uses: actions-for-kicad/setup-kicad@v1.0
        with:
          version: '7.0'

      - name: Run `mems bom`
        env:
          MOUSER_API_KEY: ${{ secrets.MOUSER_API_KEY }}
        run: |
          pip install git+https://github.com/PWr-M3/MEMS-scripts.git
          cd ./hw
          mems bom -p ./EM-Template.kicad_sch -g Mouser TME

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HW-mems
          path: |
            hw/doc
            hw/bom
            hw/fab
