name: HW action

on:
  push:
    paths:
      - 'hw**'
      - '.github'

jobs:
  kibot:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Kibot
        uses: INTI-CMNB/KiBot@v2_k7
        with:
          config: ./hw/.kibot.yaml
          dir: ./hw
          board: ./hw/EM-Template.kicad_pcb
          schema: ./hw/EM-Template.kicad_sch

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run `mems bom`
        run:
          pip install git+https://github.com/PWr-M3/MEMS-scripts.git
          mems bom -g Mouser TME

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HW-artifacts
          path: |
            hw/doc
            hw/bom
            hw/fab
